# Problem 2.2
## (a)

We have a matrix in upper triangular form as

\begin{equation}
    U_1 = 
    \begin{bmatrix}
        a_{(1, 1)} & a_{(1, 2)} & a_{(1, 3)} \\
        0 & a_{(2, 2)} & a_{(2, 3)} \\
        0 & 0 & a_{(3, 3)}
    \end{bmatrix}
\end{equation}

and another upper triangular matrix as

\begin{equation}
    U_2 = 
    \begin{bmatrix}
        b_{(1, 1)} & b_{(1, 2)} & b_{(1, 3)} \\
        0 & b_{(2, 2)} & b_{(2, 3)} \\
        0 & 0 & b_{(3, 3)}
    \end{bmatrix}
\end{equation}

Let us multiply these two matrices, $U_3 = U_1U_2$.

\begin{equation}
    U_3 = 
    \begin{bmatrix}
        a_{(1, 1)}b_{(1, 1)} & a_{(1, 1)}b_{(1, 2)} + a_{(1, 2)}b_{(2, 2)} & a_{(1, 1)}b_{(1, 3)} + a_{(1, 2)}b_{(2, 3)} + a_{(1, 3)}b_{(3, 3)} \\
        0 & a_{(2, 2)}b_{(2, 2)} & a_{(2, 2)}b_{(2, 3)} + a_{(2, 3)}b_{(3, 3)} \\
        0 & 0 & a_{(3, 3)}b_{(3, 3)}
    \end{bmatrix}
\end{equation}

We have upper triangular form matrix, $U_3$, again.

In [18]:
import numpy as np
from scipy.linalg import toeplitz

In [19]:
# Create two upper triangular matrices in dimension of 'dim'
dim = 5
U1 = np.triu(np.random.random((dim, dim)))
U2 = np.triu(np.random.random((dim, dim)))

In [20]:
# Multiply these two matrices
U3 = U1 @ U2

print(U3)

[[0.04807721 0.44277041 0.03827585 0.83333373 1.20755523]
 [0.         0.50380535 0.14957325 0.92248551 1.52998491]
 [0.         0.         0.39585288 0.49694126 0.87546616]
 [0.         0.         0.         0.49685189 0.38616361]
 [0.         0.         0.         0.         0.25597905]]


## (b)

We have a matrix in Toeplitz form as

\begin{equation}
    T_1 = 
    \begin{bmatrix}
        a_{(1, 1)} & a_{(1, 2)} & a_{(1, 3)} \\
        a_{(2, 1)} & a_{(1, 1)} & a_{(2, 3)} \\
        a_{(3, 1)} & a_{(2, 1)} & a_{(1, 1)}
    \end{bmatrix}
\end{equation}

and another Toeplitz matrix as

\begin{equation}
    T_2 = 
    \begin{bmatrix}
        b_{(1, 1)} & b_{(1, 2)} & b_{(1, 3)} \\
        b_{(2, 1)} & b_{(1, 1)} & b_{(2, 3)} \\
        b_{(3, 1)} & b_{(2, 1)} & b_{(1, 1)}
    \end{bmatrix}
\end{equation}

Let us multiply these two matrices, $T_3 = T_1T_2$.

\begin{equation}
    T_3 = 
    \begin{bmatrix}
        a_{(1, 1)}b_{(1, 1)} + a_{(1, 2)}b_{(2, 1)} + a_{(1, 3)}b_{(3, 1)} & a_{(1, 1)}b_{(1, 2)}+ a_{(1, 2)}b_{(1, 1)} + a_{(1, 3)}b_{(2, 1)}& a_{(1, 1)}b_{(1, 3)} + a_{(1, 3)}b_{(1, 1)} + a_{(1, 2)}b_{(2, 3)} \\
        a_{(1, 1)}b_{(2, 1)} + a_{(2, 1)}b_{(1, 1)} + a_{(2, 3)}b_{(3, 1)}& a_{(1, 1)}b_{(1, 1)} + a_{(2, 1)}b_{(1, 2)} + a_{(2, 3)}b_{(2, 1)}& a_{(1, 1)}b_{(2, 3)} + a_{(2, 1)}b_{(1, 3)} + a_{(2, 3)}b_{(1, 1)} \\
        a_{(1, 1)}b_{(3, 1)} + a_{(2, 1)}b_{(2, 1)} + a_{(3, 1)}b_{(1, 1)}& a_{(1, 1)}b_{(2, 1)} + a_{(2, 1)}b_{(1, 1)} + a_{(3, 1)}b_{(1, 2)}& a_{(1, 1)}b_{(1, 1)} + a_{(2, 1)}b_{(2, 3)} + a_{(3, 1)}b_{(1, 3)}
    \end{bmatrix}
\end{equation}

It is sufficient to look at diagonal part of $T_3$. One of the properties which Toeplitz matrix requires that all diagonal elements are equal. However, we do not have equal diagonal elements. <ins>$T_3$ is not Toeplitz matrix</ins>.

In [22]:
# Create two Toeplitz matrices in dimension of 'dim'
dim = 5
T1 = toeplitz(np.random.random((dim, 1)), np.random.random((dim, 1)))
T2 = toeplitz(np.random.random((dim, 1)), np.random.random((dim, 1)))

In [23]:
# Multiply these two matrices
T3 = T1 @ T2

print(T3)

[[0.98945474 1.64552748 1.78939969 1.66348159 2.51886674]
 [0.95027427 1.59868823 2.14205783 1.83136139 2.37658495]
 [1.05174302 1.57581474 2.10781311 2.18160238 2.56525616]
 [1.04604927 1.62400025 2.06410173 2.25862227 2.79780256]
 [1.09685276 1.58934413 2.07283461 2.13227777 2.87973971]]


## (c)

We have a matrix in centrosymmetric form as

\begin{equation}
    C_1 = 
    \begin{bmatrix}
        a_{(1, 1)} & a_{(1, 2)} & a_{(1, 3)} \\
        a_{(2, 1)} & a_{(2, 2)} & a_{(1, 2)} \\
        a_{(1, 3)} & a_{(2, 1)} & a_{(1, 1)}
    \end{bmatrix}
\end{equation}

and another centrosymmetric matrix as

\begin{equation}
    C_2 = 
    \begin{bmatrix}
        b_{(1, 1)} & b_{(1, 2)} & b_{(1, 3)} \\
        b_{(2, 1)} & b_{(2, 2)} & b_{(1, 2)} \\
        b_{(1, 3)} & b_{(2, 1)} & b_{(1, 1)}
    \end{bmatrix}
\end{equation}

Let us multiply these two matrices, $C_3=C_1C_2$.

\begin{equation}
    C_2 = 
    \begin{bmatrix}
        a_{(1, 1)}b_{(1, 1)} + a_{(1, 2)}b_{(2, 1)} + a_{(1, 3)}b_{(3, 1)}& a_{(1, 1)}b_{(1, 2)} + a_{(1, 2)}b_{(1, 1)} + a_{(1, 3)}b_{(2, 1)}& a_{(1, 1)}b_{(1 ,3)} + a_{(1, 2)}b_{(1, 2)} + a_{1, 3)}b_{1, 1)} \\
        a_{2, 1)}b_{1, 1)} + a_{1, 2)}b_{3, 1)} + a_{2, 2)}b_{2, 1)}& a_{1, 2)}b_{2, 1)} + a_{2, 1)}b_{1, 2)} + a_{2, 2)}b_{1 , 1)}& a_{1, 2)}b_{1, 1)} + a_{2, 1)}b_{1, 3)} + a_{2, 2)}b_{1, 2)} \\
        a_{1, 1)}b_{3, 1)} + a_{2, 1)}b_{2, 1)} + a_{3, 1)}b_{1, 1)}& a_{1, 1)}b_{2, 1)} + a_{2, 1)}b_{1, 1)} + a_{3, 1)}b_{1, 2)}& a_{1, 1)}b_{1, 1)} + a_{2, 1)}b_{1, 2)} + a_{3, 1)}b_{1, 3)}
    \end{bmatrix}
\end{equation}

It is sufficient to check if $C_3$ is symmetric according to cross diagonal. We do not have symmetric $C_3$ matrix which is symmetric around the cross diagonal. <ins>$C_3$ is not centrosymmetric matrix</ins>.

In [30]:
# Create two centrosymmetric matrices in dimension of 'dim'
dim = 5
C1 = np.array(([1, 2, 3], [4, 5, 2], [3, 4, 1]))
C2 = np.array(([6, 7, 8], [9, 10, 7], [8, 9, 6]))

In [31]:
# Multiply these two matrices
C3 = C1 @ C2

print(C3)

[[48 54 40]
 [85 96 79]
 [62 70 58]]
