# Problem 2.4
## (a)

According to Eq. (2.39), least squares solution is

\begin{equation}
    x_0 = \big(A^HA\big)^{-1}A^Hb
\end{equation}

We have 

\begin{equation}
    A = 
    \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
        1 & 1
    \end{bmatrix}, \; b = 
                          \begin{bmatrix}
                               1 \\
                               1 \\
                               0
                          \end{bmatrix}
\end{equation}

Then, least squares solution is as follows

In [9]:
import numpy as np

In [10]:
# Set the matrices
A = np.array(([1, 0], [0, 1], [1, 1]))
b = np.array([1, 1, 0]).reshape((3, 1))

In [11]:
LSS = np.linalg.inv(A.T @ A) @ A.T @ b

print(LSS)

[[0.33333333]
 [0.33333333]]


## (b)

In the light of the Eq. (2.41), projection matrix is given as 

\begin{equation}
    P_A = A\big(A^HA\big)^{-1}A^H
\end{equation}

Let us find the projection matrix.

In [12]:
# Find Projection Matrix
PA = A @ np.linalg.inv(A.T @ A) @ A.T

print(PA)

[[ 0.66666667 -0.33333333  0.33333333]
 [-0.33333333  0.66666667  0.33333333]
 [ 0.33333333  0.33333333  0.66666667]]


## (c)

Below equation is given

\begin{equation}
    \hat{b} = P_Ab
\end{equation}

where $\hat{b}$ is the best approximation.

In [14]:
# Find the best approximation
b_hat = PA @ b

print(b_hat)

[[0.33333333]
 [0.33333333]
 [0.66666667]]


## (d)

Let us find the new projection function as given below

\begin{equation}
    P_A^\perp = I - P_A
\end{equation}

In [17]:
# Find new projection function
PA_orthogonal = np.identity(PA.shape[0]) - PA

In [21]:
# Find the best approximation for PA_orthogonal as given in (c) section
b_orthogonal = PA_orthogonal @ b

print(b_orthogonal)

[[ 0.66666667]
 [ 0.66666667]
 [-0.66666667]]


One who wants to check if two nonzero vectors are orthogonal or not can utilize inner product as given in Eq. (2.24)

\begin{equation}
    <a, b> = ||a||.||b||.cos\big(\theta\big)
\end{equation}

To check inner product, we have to find it first as follows

\begin{equation}
    <a, b> = a^Hb
\end{equation}

If inner product is equal to $0$, two nonzero vectors are said to be orthogonal.

In [24]:
# Find inner product
innProd = b_hat.T @ b_orthogonal

In [30]:
# Find the THETA angle in degrees 
theta = np.rad2deg(np.arccos(innProd / (np.linalg.norm(b_hat) * np.linalg.norm(b_orthogonal))))

print(theta)

[[90.]]


$\theta = 90$, then these two nonzero vectors are orthogonal. 

$P_A^\perp$, which is perpendicular to $P_A$, represents the rotation matrix to rotate $b$ through $b^\perp$.